## Configuration file for NextPay

config-version: 1

database:
  ## available options: sqlite, mysql
  type: sqlite
  ## options for mysql
  host: 'local'
  port: 3306
  database: 'database'
  username: 'root'
  password: 'password'
  max-pool-size: 10

## General Options
## Interval in seconds
auto-save-interval: 300

## Interval to block refreshing in GUIs to often (In milliseconds)
block-refresh-time: 2000