name: NextPay
description: Standalone economy plugin
version: ${version}

main: me.myraclez.nextPay.NextPay
api-version: '1.21'
load: POSTWORLD

depend:
  - Vault

authors: [ myraclez ]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.projectlombok:lombok:1.18.44
  - com.mysql:mysql-connector-j:9.3.0

loadbefore:
  - DonutOrder
  - DonutSell

permissions:
  nextpay.baltop:
    default: true
  nextpay.pay:
    default: true
  nextpay.bal:
    default: true
  nextpay.admin:
    default: op
  nextpay.toggle:
    default: true